---

- name: Install NFS server packages on Debian
  package:
    name: nfs-kernel-server
    state: latest
  when: ansible_os_family == "Debian"

- name: Install NFS server packages on RedHat
  package:
    name: nfs-utils
    state: latest
  when: ansible_os_family == "RedHat"

- name: Ensure nfs-kernel-server is running and starts on boot
  service:
    name: nfs-kernel-server
    state: started
    enabled: yes

- name: Check every fs exists
  file:
    path: "{{ item.fs }}"
    state: directory
  with_items: "{{ nfs_exports }}"

- name: Configure /etc/exports
  lineinfile:
    path: /etc/exports
    regexp: "^{{ item.fs }}[\t| ]"
    line: "{{ item.fs }}	{{ item.client }}({{ item.options }})"
  notify: Reload exports
  with_items: "{{ nfs_exports }}"